# This is a global registry for public HSDP services
# containing most static configuration. Its main purpose is to
# reduce configuration parameters and drive automation of the
# platform further by having a human and machine readable source of
# common configuration parameters
#
# Before using it as your source of truth please confirm it has
# the expected values.
#
# Also it goes without saying, but we will say it anyway:
# It is your responsibility to ensure correct configuration of
# your deployments.
#
# If you spot errors or incomplete information please raise a
# PR. Thanks!
#
# Definitions:
#
# Region - a geographical region where services are deployed
# Environment - a stage within a geographical region to aid in phased deployment
# Service - a consumable software service
# Instance - a specific deployment of a service
#
# Hierarchy example:
#
# Earth
#   Region us-east
#     Service
#       cf
#     Environment client-test
#       Service
#         iam
#	  idm
#     Environment production
#       Service
#         iam
#         idm
#
#   Region eu-west
#     Environment client-test
#       Service
#         iam
#         idm
#     Environment production
#       Service
#         iam
#         idm
#
# Nesting syntax: [region.environment.service.instance]
#
# Services can be tied to a region or an environment
# We also anticipate global services at some point
# Example of a region bound service: Cloud foundry
# Example of a environment bound service: IAM

# Service STL
[region.dev.service.stl]
url = "https://console.na3.hsdp.io/api/stl/user/v1/graphql"
domain = "na1.vpn.hsdp.io"
[region.us-east.service.stl]
url = "https://console.na1.hsdp.io/api/stl/user/v1/graphql"
domain = "na1.vpn.hsdp.io"
[region.eu-west.service.stl]
url = "https://console.eu1.hsdp.io/api/stl/user/v1/graphql"
domain = "emea1.vpn.hsdp.io"

# Service UAA
[region.us-east.service.uaa]
url = "https://uaa.cloud.pcftest.com"
[region.eu-west.service.uaa]
url = "https://uaa.eu1.phsdp.com"
[region.sa1.service.uaa]
url = "https://uaa.sys.sa1.hsdp.io"
[region.apac3.service.uaa]
url = "https://uaa.sys.ap3.hsdp.io"
[region.dev.service.uaa]
url = "https://uaa.cloud.phsdp.com"
[region.ca1.service.uaa]
url = "https://uaa.sys.ca1.hsdp.io"
[region.apac2.service.uaa]
url = "https://uaa.ap-ne.philips-healthsuite.com"

# Service IAM
[region.us-east.env.client-test.service.iam]
url = "https://iam-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.iam]
url = "https://iam-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.iam]
url = "https://iam-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.iam]
url = "https://iam-service.eu-west.philips-healthsuite.com"
[region.sa1.env.prod.service.iam]
url = "https://iam-service.sa1.hsdp.io"
[region.apac2.env.prod.service.iam]
url = "https://iam-service.ap-ne.philips-healthsuite.com"
[region.apac3.env.prod.service.iam]
url = "https://iam-service.ap3.hsdp.io"
[region.us-east.env.dev.service.iam]
url = "https://iam-development.us-east.philips-healthsuite.com"
[region.us-east.env.preview.service.iam]
url = "https://iam.us-east-1.stg-foundation-security.hsp.philips.com"
[region.cn1.env.prod.service.iam]
url = "https://iam-service.cn1.philips-healthsuite.com.cn"
[region.ca1.env.prod.service.iam]
url = "https://iam-service.ca1.hsdp.io"

# Service IDM
[region.us-east.env.client-test.service.idm]
url = "https://idm-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.idm]
url = "https://idm-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.idm]
url = "https://idm-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.idm]
url = "https://idm-service.eu-west.philips-healthsuite.com"
[region.sa1.env.prod.service.idm]
url = "https://idm-service.sa1.hsdp.io"
[region.apac2.env.prod.service.idm]
url = "https://idm-service.ap-ne.philips-healthsuite.com"
[region.apac3.env.prod.service.idm]
url = "https://idm-service.ap3.hsdp.io"
[region.us-east.env.dev.service.idm]
url = "https://idm-development.us-east.philips-healthsuite.com"
[region.us-east.env.preview.service.idm]
url = "https://idm.us-east-1.stg-foundation-security.hsp.philips.com"
[region.cn1.env.prod.service.idm]
url = "https://idm-service.cn1.philips-healthsuite.com.cn"
[region.ca1.env.prod.service.idm]
url = "https://idm-service.ca1.hsdp.io"

# Service DBS
[region.eu-west.env.client-test.service.dbs]
url = "https://databroker-client-test.eu01.connect.hsdp.io/client-test/connect/databroker"

# Service LOGGING
[region.eu-west.env.client-test.service.logging]
url = "https://logingestor2-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.logging]
url = "https://logingestor2.eu-west.philips-healthsuite.com"
[region.us-east.env.client-test.service.logging]
url = "https://logingestor2-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.logging]
url = "https://logingestor2.us-east.philips-healthsuite.com"
[region.sa1.env.prod.service.logging]
url = "https://logingestor2.sa1.hsdp.io"
[region.apac3.env.prod.service.logging]
url = "https://logingestor2.ap3.hsdp.io"
[region.ca1.env.prod.service.logging]
url = "https://logingestor2.ca1.hsdp.io"
[region.pl.env.client-test.logging]
url = "https://logingestor2-client-test.cf.pl.hsdp.io"

# Service LOGQUERY
[region.eu-west.env.client-test.service.logquery]
url = "https://logquery-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.logquery]
url = "https://logquery.eu-west.philips-healthsuite.com"
[region.us-east.env.client-test.service.logquery]
url = "https://logquery-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.logquery]
url = "https://logquery.us-east.philips-healthsuite.com"
[region.sa1.env.prod.service.logquery]
url = "https://logquery.sa1.hsdp.io"
[region.apac3.env.prod.service.logquery]
url = "https://logquery.ap3.hsdp.io"
[region.ca1.env.prod.service.logquery]
url = "https://logquery.ca1.hsdp.io"

# Service CONNECT-MDM
[region.us-east.env.client-test.service.connect-mdm]
url = "https://connect-mdm-client-test.us01.connect.hsdp.io/connect/mdm"
[region.us-east.env.prod.service.connect-mdm]
url = "https://connect-mdm.us01.iot.hsdp.io/connect/mdm"
[region.eu-west.env.client-test.service.connect-mdm]
url = "https://connect-mdm-client-test.eu01.connect.hsdp.io/connect/mdm"
[region.eu-west.env.prod.service.connect-mdm]
url = "https://connect-mdm.eu01.iot.hsdp.io/connect/mdm"
[region.cn1.prod.service.connect-mdm]
url = "https://connect-mdm.cn1.iot.philips-healthsuite.com.cn/connect/mdm"

# Service PROVISIONING
[region.us-east.env.client-test.service.provisioning]
url = "https://provisioning-client-test.us01.connect.hsdp.io/client-test/connect/provisioning"
[region.eu-west.env.client-test.service.provisioning]
url = "https://provisioning-client-test.eu01.connect.hsdp.io/client-test/connect/provisioning"
[region.eu-west.env.prod.service.provisioning]
url = "https://provisioning.eu01.iot.hsdp.io/connect/provisioning"
[region.us-east.env.prod.service.provisioning]
url = "https://provisioning.us01.iot.hsdp.io/connect/provisioning"

# Service DISCOVERY
[region.us-east.env.client-test.service.discovery]
url = "https://discovery-client-test.us01.connect.hsdp.io/client-test/core/discovery"
[region.eu-west.env.client-test.service.discovery]
url = "https://discovery-client-test.eu01.connect.hsdp.io/client-test/core/discovery"
[region.eu-west.env.prod.service.discovery]
url = "https://discovery.eu01.iot.hsdp.io/core/discovery"
[region.us-east.env.prod.service.discovery]
url = "https://discovery.us01.iot.hsdp.io/core/discovery"

# Service BLR
[region.us-east.env.client-test.service.blr]
url = "https://blobrepository-client-test.us01.connect.hsdp.io/connect/blobrepository"
[region.eu-west.env.client-test.service.blr]
url = "https://blobrepository-client-test.eu01.connect.hsdp.io/connect/blobrepository"
[region.cn1.prod.service.blr]
url = "https://blobrepository.cn1.iot.philips-healthsuite.com.cn/connect/blobrepository"
[region.eu-west.env.prod.service.blr]
url = "https://blobrepository.eu01.iot.hsdp.io/connect/blobrepository"
[region.us-east.env.prod.service.blr]
url = "https://blobrepository.us01.iot.hsdp.io/connect/blobrepository"

# Service IOT
[region.us-east.env.client-test.service.iot]
url = "wss://a2vgioynsisd7n-ats.iot.us-east-1.amazonaws.com/mqtt?topic-prefix=client-test"
[region.eu-west.env.prod.service.iot]
url = "wss://a370yzaa002yx5-ats.iot.eu-west-1.amazonaws.com/mqtt?topic-prefix=prod"
[region.cn1.prod.service.iot]
url = "wss://aqrsmt9m297sm.ats.iot.cn-north-1.amazonaws.com.cn/mqtt?topic-prefix=prod"
